backend:
  name: git-gateway
  branch: main

site_url: https://starlit-gaufre-c396c3.netlify.app/
display_url: https://starlit-gaufre-c396c3.netlify.app/admin

media_folder: "images/uploads"
public_folder: "/images/uploads"

publish_mode: editorial_workflow

collections:
  - name: "articles"
    label: "Articles"
    folder: "content/articles"
    create: true
    slug: "{{slug}}"
    format: "json"

    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publication", name: "publication", widget: "string" }
      - { label: "Category", name: "category", widget: "select", options: [
          "Palestine",
          "Media Criticism",
          "Housing",
          "Labor",
          "Education",
          "Climate",
          "New York",
          "Electoral Politics"
        ] }
      - { label: "Link", name: "link", widget: "string" }
      - { label: "Featured", name: "featured", widget: "boolean", default: false }
      - { label: "Image", name: "image", widget: "image", required: false }